---
title: "Load Package"
author: "Danielle Ethier"
date: "28/08/2020"
output: html_document
---

# 2 Loading R Packages {#loadp2}

The functionalities of some packages may require updated versions of [R](https://www.r-project.org/) and [RStudio](https://www.rstudio.com). To avoid errors, please ensure you are using the most recent releases of R and RStudio, and update your R packages using `update.packages()` in the R console.

## 2.1 Installing the NatureCounts package {#loadp2.1}


You can install this developmental version of naturecounts from GitHub with the remotes package:

```
install.packages("remotes")
remotes::install_github("BirdStudiesCanada/naturecounts")

```
After installation, you need to load the package each time you open a new R session.

```
library(naturecounts)

```

## 2.2 Installing additional packages {#loadp2.2}

Throughout the book we use [tidyverse](https://www.tidyverse.org/), which is a collection of R packages for data science, including tidyr, dplyr, ggplot2, and lubridate for managing and manipulating dates. This package can be installed from CRAN, as follows:

```

install.packages("tidyverse")
library(tidyverse)

````

Congratulations! You have installed the NatureCounts R package. In the next chapter we will develop a better understand of the data structure, access level, and authorizations before learn to download data.
