---
title: "Load Data"
author: "Danielle Ethier"
date: "28/08/2020"
output: html_document
---

# 3 Accessing NatureCounts Data {#Data3}

This chapter begins with a brief introduction to the structure of the NatureCounts database, followed by a description of access levels and how to create a user account. We then provide instructions on how to view and download data from various collections. Last, we demonstate how to apply filters to the data request.    

## 3.1 Data Structure {#Data3.1}

The [Bird Monitoring Data Exchange](https://www.birdscanada.org/birdmon/default/nc_bmde.jsp) (BMDE) was developed to be a standardized data exchange schema to promote the sharing and analysis of avain observational data . The schema is the core sharing standard of the [Avian Knowledge Network](www.avianknowledge.net).The BMDE (currently version 2.0) includes 169 *core* fields that are capable of capturing all metrics and descriptors associated with a bird observation.The BMDE schema was extended in 2018, and the *complete* version now includes 265 fields.

By default the NatureCounts package downloads the data with the *minimum* set of fields/columns. However, for more advanced applications, users may wish to specify which fields/columns to return using the `field_set` and `fields` options in the `nc_data_dl` function. For help with this feature, type `?nc_data_dl` into the R console.   

## 3.2 Levels of Data Access {#Data3.2}

NatureCounts host many datasets, representing in excess of 100 millions of occurrence records, with a primary focus on Canadian bird monitoring. Many of those datasets are from project lead by Birds Canada and/or its partners. While we thrive to make our data as openly available as possible, we also need to recognize the need of our partners and funders.

NatureCounts has five [Levels of Data Access](https://www.birdscanada.org/birdmon/default/nc_access_levels.jsp), which define how each dataset can be used. Those levels are set individually for each dataset, in consultation with the various partners and data custodian involved.

-Level 0: most restricted (archival only)
-Level 1: archival only, metadata visible
-Level 2: data used for visualizations only
-Level 3: data available to third parties by request
-Level 4: data shared with external portals and avaialble by request
-Level 5: open access

All contributing members of NatureCounts have complete authority over the use of the data they have provided, and can withhold data at any time from any party or application. All users of any NatureCounts data must clearly acknowledge the contribution of the members who are making data available. Each dataset comes with its own [Data Sharing Policy](https://www.birdscanada.org/birdmon/default/nc_data_sharing.jsp) that defines the various conditions for data usage.

## 3.3 Authorizations {#Data3.3}

To access data using the NatureCounts R package, you must [sign up](https://www.birdscanada.org/birdmon/default/register.jsp) for a free account. Further, if you would like to access Level 3 or 4 collections you must make a [data request](https://www.birdscanada.org/birdmon/default/searchquery.jsp). For step-by-step visual instructions, we encourage you to watch: [NatureCounts: An Introductory Tutorial](link to be provided).

## 3.4 Viewing information about NatureCounts collections {#Data3.4}

First, let's use the NatureCounts R package to view the available collections. To do this we use the `nc_count` function. You can view *all* the avaiable collections and the number of observations using the default setting. 

```
nc_count() 

```
Or you can view the collections for which you have access using your username/password.

```
nc_count(username = "sample")

```
Further refinements using filters can be applied to the `nc_count` function. These will be demonstrated in the Fitlers section. 

**Exercise 1: Try using your personal username/password to see which collections are available to you. What if there is a collection you would like to access that is not listed under your username. How would you go about requesting access to these data?**  Keep reading to reveal the answer to this question. 

## 3.5 Downloading NatureCounts date {#Data3.5}

Open access collections are available without a username/password.   

```
#Insert example

```

However, to access Level 3 or 4 collections (see section [3.2](#Data3.2)) you must [sign up](https://www.birdscanada.org/birdmon/default/register.jsp) for a free NatureCounts account and request permission to access the data using the [webportal](https://www.birdscanada.org/birdmon/default/searchquery.jsp). For step-by-step visual instructions, we encourage you to watch: [NatureCounts: An Introductory Tutorial](link to be provided). You will recieve an email confirmation when your request has been approves, which will contain your `request_id`. This number will be used to download your newly aquired dataset into R.   

```

#Insert example

```
## 3.6 Applying Filters {#Data3.6}

`nc_count()` and `nc_data_dl()` have a variety of arguments that allow you to filter the data prior to downloading. These options include: collections, species, years, doy (day-of-year), region, and site_type. 


The users can specify up to 3 of these options in the download process. One of these will likely alway be collections, since authorization is given idenpendently for each collection. For nc_data_dl() you have the additional arguments fields_set and fields with which you can customize which fields/columns to include in your download.
